### PR TITLE
add export_to_path method, change nbs.00_core

### PR DESCRIPTION
**Pull request by dogukantai**
An optional core method call to export the processed data source to a desired path.

_Example output with the base wikitext filter & clean operations:_

```
[07/02/23 10:25:46] INFO: core.py:61 - Running datasource: wikitext

INFO: squeakily.core - Running datasource: wikitext

INFO: core.py:34 - Running filter: check_char_repetition on text

INFO: squeakily.core - Running filter: check_char_repetition on text

INFO: core.py:34 - Running filter: check_flagged_words on text

INFO: squeakily.core - Running filter: check_flagged_words on text

INFO: core.py:81 - Running cleaner: remove_empty_lines on text

INFO: squeakily.core - Running cleaner: remove_empty_lines on text

INFO: core.py:81 - Running cleaner: normalize_whitespace on text

INFO: squeakily.core - Running cleaner: normalize_whitespace on text

Creating CSV from Arrow format: 100%

19/19 [00:00<00:00, 61.56ba/s]

INFO: core.py:138 - Exported wikitext dataset to /content/x/wikitext.csv

INFO: squeakily.core - Exported wikitext dataset to /content/x/wikitext.csv
```

### CODE REVIEW

**Comment by ncoop57** [comment]
Thanks so much for the PR! looking into it now

**Review by ncoop57 — CHANGES_REQUESTED** [review]
Could you please add a output_type argument for the type of file to export as? For example in this use case you have it for "csv", but others might want to have it export to json or parquets.

Additionally, please add doc strings to the arguments for easier readability

**Comment by dogukantai** [comment]
> 

Thanks for the quick review! Sure, I will implement these soon 👍

**Comment by dogukantai** [comment]
Hey @ncoop57, updated the method according to review changes.

Example output after review changes with the base wikitext filter & clean operations:

```bash
[07/09/23 07:29:41] INFO     Running datasource: wikitext                                                [core.py](file:///content/squeakily/squeakily/core.py):[61](file:///content/squeakily/squeakily/core.py#61)
INFO:squeakily.core:Running datasource: wikitext
                    INFO     Running filter: check_char_repetition on text                               [core.py](file:///content/squeakily/squeakily/core.py):[34](file:///content/squeakily/squeakily/core.py#34)
INFO:squeakily.core:Running filter: check_char_repetition on text
[07/09/23 07:29:43] INFO     Running filter: check_flagged_words on text                                 [core.py](file:///content/squeakily/squeakily/core.py):[34](file:///content/squeakily/squeakily/core.py#34)
INFO:squeakily.core:Running filter: check_flagged_words on text
[07/09/23 07:29:45] INFO     Running cleaner: remove_empty_lines on text                                 [core.py](file:///content/squeakily/squeakily/core.py):[81](file:///content/squeakily/squeakily/core.py#81)
INFO:squeakily.core:Running cleaner: remove_empty_lines on text
[07/09/23 07:29:48] INFO     Running cleaner: normalize_whitespace on text                               [core.py](file:///content/squeakily/squeakily/core.py):[81](file:///content/squeakily/squeakily/core.py#81)
INFO:squeakily.core:Running cleaner: normalize_whitespace on text
[07/09/23 07:29:49] INFO     JSON indication setted as records                                          [core.py](file:///content/squeakily/squeakily/core.py):[145](file:///content/squeakily/squeakily/core.py#145)
INFO:squeakily.core:JSON indication setted as records
Creating json from Arrow format: 100%
19/19 [00:00<00:00, 211.88ba/s]
                    INFO     Exported wikitext dataset to /content/x/wikitext.json                      [core.py](file:///content/squeakily/squeakily/core.py):[151](file:///content/squeakily/squeakily/core.py#151)
INFO:squeakily.core:Exported wikitext dataset to /content/x/wikitext.json
```

**Comment by ncoop57** [comment]
Alright, this is perfect! I just modify the README to use a callout rather than a comment for describing how to use this feature. Thank you very much for adding this!!

**Pull request merged**
